### ISSUE TITLE
Requesting a new tag

### ISSUE THREAD

**Issue by choonge** [whiteoctober/WhiteOctoberSwiftMailerDBBundle#15]
Hello,

I would like the use the change in 5745dec99c5db3ced2d04987c61f43266e3a79cf but would prefer not to lock to dev-master in my composer.json. Could you create a new tag which includes the latest status?

Thanks in advance!

**Comment by richsage** [comment]
No problems - 1.0.4 done :-)

**Comment by choonge** [comment]
thanks!:)
