### ISSUE TITLE
How to trigger the email in WhiteOctoberSwiftmailer Db Bundle?

### ISSUE THREAD

**Issue by vishalpawar-tudip** [whiteoctober/WhiteOctoberSwiftMailerDBBundle#24]
Hi All,
 
I am a bit confused about the configuration of the bundle. I have configured all the steps provided in the Readme section but not able to get started it with.

I did the following steps:
1. Installed and configured the bundle.
2. Added the bundle entry in the Appkernel.php
2. Configured the required settings in config.yml
3. Created the entity which implements the EmailInterface provided in the bundle.
4. Configured the spool type to 'db'.

Is anything missing in the steps, please let us know asap?
By default, swiftmailer uses the command "php app/console swiftmailer:spool:send"
I just wanted to trigger the email which will be spooled from DB and the command which used to execute it.
Any help is really appreciated.
Thanks!

**Comment by sampart** [comment]
Hi @vishalpawar-tudip, sorry for the delay in replying.

Have you included code to send an email in your app?  https://symfony.com/doc/3.4/email.html#sending-emails might help here.

Let me know how you get on.  Thanks

**Comment by vishalpawar-tudip** [comment]
Thanks for reply @sampart.
I have updated the code, now it is working fine.
